/**
 * Mock Transaction Data
 * In production, this would be fetched from an API
 */

import { SUBSIDY_STATUS, RFID_STATUS, VEHICLE_TYPE, FUEL_TYPE } from "./types";

export const mockTransactions = [
  {
    time: "14:23:45",
    spbu: "SPBU Pasteur",
    dispenser: "A1",
    vehicle: VEHICLE_TYPE.MOTORCYCLE,
    brand: "Honda",
    color: "Red",
    plate: "D 1234 ABC",
    fuel: FUEL_TYPE.PERTALITE,
    volume: "5.2",
    subsidy: SUBSIDY_STATUS.VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "14:22:31",
    spbu: "SPBU Dago",
    dispenser: "A2",
    vehicle: VEHICLE_TYPE.CAR,
    brand: "Toyota",
    color: "White",
    plate: "D 5678 XYZ",
    fuel: FUEL_TYPE.PERTAMAX,
    volume: "20.5",
    subsidy: SUBSIDY_STATUS.NOT_APPLICABLE,
    rfid: RFID_STATUS.NOT_APPLICABLE,
    fraud: null,
  },
  {
    time: "14:21:18",
    spbu: "SPBU Gatot Subroto",
    dispenser: "B1",
    vehicle: VEHICLE_TYPE.MOTORCYCLE,
    brand: "Yamaha",
    color: "Blue",
    plate: "B 9876 DEF",
    fuel: FUEL_TYPE.PERTALITE,
    volume: "4.8",
    subsidy: SUBSIDY_STATUS.NOT_VALID,
    rfid: RFID_STATUS.NOT_VALID,
    fraud: null,
  },
  {
    time: "14:20:02",
    spbu: "SPBU Pasteur",
    dispenser: "B2",
    vehicle: VEHICLE_TYPE.CAR,
    brand: "Mitsubishi",
    color: "Black",
    plate: "D 2468 GHI",
    fuel: FUEL_TYPE.SOLAR,
    volume: "35",
    subsidy: SUBSIDY_STATUS.VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "14:18:47",
    spbu: "SPBU Pajajaran",
    dispenser: "A1",
    vehicle: VEHICLE_TYPE.TRUCK,
    brand: "Hino",
    color: "White",
    plate: "F 1357 JKL",
    fuel: FUEL_TYPE.SOLAR,
    volume: "80",
    subsidy: SUBSIDY_STATUS.NOT_VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "14:17:33",
    spbu: "SPBU Dago",
    dispenser: "A1",
    vehicle: VEHICLE_TYPE.MOTORCYCLE,
    brand: "Suzuki",
    color: "Green",
    plate: "D 8642 MNO",
    fuel: FUEL_TYPE.PERTALITE,
    volume: "6",
    subsidy: SUBSIDY_STATUS.VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "14:15:20",
    spbu: "SPBU Ahmad Yani Surabaya",
    dispenser: "A1",
    vehicle: VEHICLE_TYPE.CAR,
    brand: "Honda",
    color: "Silver",
    plate: "L 1122 PQR",
    fuel: FUEL_TYPE.PERTAMAX,
    volume: "22",
    subsidy: SUBSIDY_STATUS.NOT_APPLICABLE,
    rfid: RFID_STATUS.NOT_APPLICABLE,
    fraud: null,
  },
  {
    time: "14:10:05",
    spbu: "SPBU Gatot Subroto Medan",
    dispenser: "A2",
    vehicle: VEHICLE_TYPE.MOTORCYCLE,
    brand: "Kawasaki",
    color: "Black",
    plate: "BK 3344 STU",
    fuel: FUEL_TYPE.PERTALITE,
    volume: "5.5",
    subsidy: SUBSIDY_STATUS.VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "14:08:42",
    spbu: "SPBU Thamrin",
    dispenser: "B1",
    vehicle: VEHICLE_TYPE.CAR,
    brand: "BMW",
    color: "Black",
    plate: "B 5566 VWX",
    fuel: FUEL_TYPE.PERTAMAX_TURBO,
    volume: "28",
    subsidy: SUBSIDY_STATUS.NOT_APPLICABLE,
    rfid: RFID_STATUS.NOT_APPLICABLE,
    fraud: null,
  },
  {
    time: "14:05:18",
    spbu: "SPBU Gejayan",
    dispenser: "A1",
    vehicle: VEHICLE_TYPE.MOTORCYCLE,
    brand: "Honda",
    color: "Red",
    plate: "AB 7788 YZA",
    fuel: FUEL_TYPE.PERTALITE,
    volume: "4.9",
    subsidy: SUBSIDY_STATUS.VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "13:58:30",
    spbu: "SPBU BSD Tangerang",
    dispenser: "B2",
    vehicle: VEHICLE_TYPE.CAR,
    brand: "Toyota",
    color: "White",
    plate: "B 9900 BCD",
    fuel: FUEL_TYPE.SOLAR,
    volume: "40",
    subsidy: SUBSIDY_STATUS.VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "13:45:12",
    spbu: "SPBU Pasteur",
    dispenser: "A1",
    vehicle: VEHICLE_TYPE.CAR,
    brand: "Mazda",
    color: "Blue",
    plate: "D 7890 EFG",
    fuel: FUEL_TYPE.PERTAMAX,
    volume: "25",
    subsidy: SUBSIDY_STATUS.NOT_APPLICABLE,
    rfid: RFID_STATUS.NOT_APPLICABLE,
    fraud: null,
  },
  {
    time: "13:30:55",
    spbu: "SPBU Slamet Riyadi",
    dispenser: "B1",
    vehicle: VEHICLE_TYPE.TRUCK,
    brand: "Isuzu",
    color: "Yellow",
    plate: "AD 1234 HIJ",
    fuel: FUEL_TYPE.SOLAR,
    volume: "95",
    subsidy: SUBSIDY_STATUS.NOT_VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "13:22:40",
    spbu: "SPBU Demang Palembang",
    dispenser: "A2",
    vehicle: VEHICLE_TYPE.CAR,
    brand: "Toyota",
    color: "Silver",
    plate: "BG 5678 KLM",
    fuel: FUEL_TYPE.PERTAMAX,
    volume: "30",
    subsidy: SUBSIDY_STATUS.NOT_APPLICABLE,
    rfid: RFID_STATUS.NOT_APPLICABLE,
    fraud: null,
  },
  {
    time: "12:58:23",
    spbu: "SPBU Banda Aceh",
    dispenser: "B1",
    vehicle: VEHICLE_TYPE.MOTORCYCLE,
    brand: "Honda",
    color: "Red",
    plate: "BL 9012 NOP",
    fuel: FUEL_TYPE.PERTALITE,
    volume: "5.8",
    subsidy: SUBSIDY_STATUS.VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "12:45:10",
    spbu: "SPBU Sunset Road Bali",
    dispenser: "A1",
    vehicle: VEHICLE_TYPE.CAR,
    brand: "Mercedes-Benz",
    color: "Black",
    plate: "DK 3456 QRS",
    fuel: FUEL_TYPE.PERTAMAX_TURBO,
    volume: "32",
    subsidy: SUBSIDY_STATUS.NOT_APPLICABLE,
    rfid: RFID_STATUS.NOT_APPLICABLE,
    fraud: null,
  },
  {
    time: "11:22:40",
    spbu: "SPBU Gatot Subroto",
    dispenser: "A1",
    vehicle: VEHICLE_TYPE.MOTORCYCLE,
    brand: "Yamaha",
    color: "Blue",
    plate: "B 1122 TUV",
    fuel: FUEL_TYPE.PERTALITE,
    volume: "5.5",
    subsidy: SUBSIDY_STATUS.VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
  {
    time: "10:15:30",
    spbu: "SPBU Ahmad Yani Banjarmasin",
    dispenser: "B1",
    vehicle: VEHICLE_TYPE.TRUCK,
    brand: "Mitsubishi Fuso",
    color: "White",
    plate: "DA 7890 WXY",
    fuel: FUEL_TYPE.SOLAR,
    volume: "120",
    subsidy: SUBSIDY_STATUS.NOT_VALID,
    rfid: RFID_STATUS.VALID,
    fraud: null,
  },
];
